# Generated by Django 3.2 on 2021-10-25 18:07

import django.core.validators
from django.db import migrations, models


def calc_price_for_old_orders(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.all():
        item.price = item.quantity * item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость товара'),
        ),
        migrations.RunPython(code=calc_price_for_old_orders, reverse_code=migrations.RunPython.noop)
    ]
