# Generated by Django 3.2 on 2021-11-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20211103_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Оплата наличными'), (2, 'Оплата картой')], default=1, verbose_name='Способ оплаты'),
        ),
    ]
