# Generated by Django 3.2 on 2021-11-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='total_price',
        ),
    ]
