# Generated by Django 3.2 on 2022-05-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Комментарий к заказу'),
        ),
    ]
